### ISSUE TITLE
Theme "vs-dark" is hardcoded and I can't change it

### ISSUE THREAD

**Issue by ionut-pruteanu** [courage007/Angular-Monaco-Editor#7]
I can't set the default theme "vs".
I use the following options and is not working:
```
    options = {
        language: 'javascript',
        lineNumbers: "off",
        theme: "vs",
    };
```
Just looking in your code I can see 
`this.unifiedTheme = "vs-dark";`
and later on used like this:
`    function (options) {
        options.theme = this.unifiedTheme; // 由于多个monaco editor实例会共享一个主题，所以这里将统一设置主题
        return options;
    };
`
I think this is the source of the problem

**Comment by courage007** [comment]
Yes, editor theme is unified by hard code. The reason why unfiying the theme in this component is that “[the base Monoco editor does not support multiple themes in different editors](https://github.com/Microsoft/monaco-editor/issues/338)”.   
It is not a good design to unify the theme to different users.  What's more, the popular editor like **Intellij idea**, **VS(Only Test VS 2017)** also use one theme for multi editor instance.  So I reopen custom theme in the **1.10.0** version.

**Comment by courage007** [comment]
Reference IDE like ****
